version: "3.9"

services:
    application:
        build: .
        restart: "on-failure"
        environment:
            DB_CREDENTIALS: "${DATABASE_USER}:${DATABASE_PASSWORD}"
            DB_ADDRESS: "database:5432"
            DB_NAME: "${DATABASE_NAME}"
        depends_on:
            database:
                condition: service_healthy
        ports:
            - "8000:8000"
        networks:
            - common

    database:
        image: postgres:15.2
        restart: "always"
        environment:
            POSTGRES_DB: "${DATABASE_NAME}"
            POSTGRES_USER: "${DATABASE_USER}"
            POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "${DATABASE_USER}", "-d", "${DATABASE_NAME}" ]
            start_period: 60s
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - "./postgresql-state:/var/lib/postgresql/data/"
        networks:
            - common

networks:
    common:
        driver: bridge
